<script setup lang="ts">
import { computed, inject, onBeforeUnmount, onMounted, reactive, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { ApiProblemError, platformApi } from '../api'
import PageHeader from '../components/PageHeader.vue'
import ResourceState from '../components/ResourceState.vue'
import { useDeviceEditor } from '../composables/useDeviceEditor'
import { runtimeLiveConnection, runtimeLiveConnectionKey } from '../composables/useRuntimeSignalR'
import { useWorkspaceStore } from '../stores/workspace'
import type { DeviceDetails, FaultRequest, ScalarValue } from '../types'

const route = useRoute(); const router = useRouter(); const workspace = useWorkspaceStore(); const live = inject(runtimeLiveConnectionKey, runtimeLiveConnection)
const deviceId = computed(() => String(route.params.deviceId)); const details = ref<DeviceDetails | null>(null); const loading = ref(true); const error = ref(''); const editing = ref(false); const editor = useDeviceEditor(); const stateDraft = reactive<Record<string, string>>({}); const tab = ref('overview'); let poll: number | undefined
const fault = reactive<FaultRequest>({ id: '', category: 'Data', target: '', type: 'Freeze', metadata: null })
const tabs = ['overview', 'state', 'definition', 'protocols', 'scenarios', 'faults', 'events']
const writable = computed(() => new Set(details.value?.definition.dataPoints.filter(point => point.access !== 'Read').map(point => point.name) ?? []))

async function load(silent = false) { if (!silent) loading.value = true; try { details.value = await platformApi.device(deviceId.value); workspace.selectedDeviceId = deviceId.value; for (const [key, value] of Object.entries(details.value.state)) stateDraft[key] = value === null ? '' : String(value) } catch (cause) { error.value = cause instanceof Error ? cause.message : String(cause) } finally { loading.value = false } }
async function act(operation: string) { try { await platformApi.lifecycle(deviceId.value, operation); await load(true) } catch (cause) { show(cause) } }
async function tick() { try { await platformApi.tick(deviceId.value, 1); await load(true) } catch (cause) { show(cause) } }
async function write(name: string, current: ScalarValue) { try { const raw = stateDraft[name] ?? ''; const value: ScalarValue = typeof current === 'boolean' ? raw.toLowerCase() === 'true' : typeof current === 'number' ? Number(raw) : raw; await platformApi.writeState(deviceId.value, name, value); await load(true) } catch (cause) { show(cause) } }
function startEdit() { if (!details.value || details.value.summary.isRunning) return; editor.load(details.value.definition); editing.value = true; tab.value = 'definition' }
async function saveDefinition() { if (!details.value) return; try { await platformApi.updateDevice(deviceId.value, { ...editor.toRequest(), version: details.value.definition.version }); editing.value = false; await load(true); workspace.notify('Device definition replaced safely') } catch (cause) { show(cause) } }
async function remove() { if (!confirm(`Delete ${deviceId.value}?`)) return; try { await platformApi.deleteDevice(deviceId.value); await router.push('/devices') } catch (cause) { show(cause) } }
async function runScenario(id: string) { try { await platformApi.runScenario(deviceId.value, id); await load(true) } catch (cause) { show(cause) } }
async function activateFault() { try { await platformApi.activateDeviceFault(deviceId.value, fault); await load(true) } catch (cause) { show(cause) } }
async function recover(id: string) { try { await platformApi.recoverDeviceFault(deviceId.value, id); await load(true) } catch (cause) { show(cause) } }
function show(cause: unknown) { error.value = cause instanceof ApiProblemError ? `${cause.message}${cause.errorCode ? ` (${cause.errorCode})` : ''}` : cause instanceof Error ? cause.message : String(cause) }
function beginPolling() { if (!poll) poll = window.setInterval(() => void load(true), 3000) }
function stopPolling() { if (poll) window.clearInterval(poll); poll = undefined }

onMounted(async () => { await load(); try { await live.start(event => { if (event.deviceId === deviceId.value) void load(true) }, beginPolling, stopPolling) } catch { beginPolling() } })
onBeforeUnmount(() => { stopPolling(); void live.stop() })
</script>

<template><main class="content wide-content"><PageHeader eyebrow="Device" :title="deviceId" description="Inspect and operate one SimulationHost. Definition edits require a stopped runtime and replace the host atomically."><RouterLink class="button-link secondary-link" to="/devices">Back to devices</RouterLink><button v-if="workspace.isAdmin" class="danger" @click="remove">Delete device</button></PageHeader>
  <div v-if="error" class="inline-error" role="alert">{{ error }}</div>
  <ResourceState :loading="loading" :error="''" :empty="!details"><template v-if="details">
    <nav class="detail-tabs" aria-label="Device details"><button v-for="name in tabs" :key="name" :class="{ active: tab === name }" @click="tab = name">{{ name }}</button></nav>
    <section v-if="tab === 'overview'" class="detail-grid"><article class="entity-card"><span class="eyebrow">Lifecycle</span><h2>{{ details.runtime.state }}</h2><p>{{ details.summary.deviceType }} · {{ details.summary.deterministic ? 'Deterministic' : 'Real time' }} · seed {{ details.summary.seed }}</p><div class="controls"><button class="primary" :disabled="!workspace.canOperate" @click="act('start')">Start / resume</button><button :disabled="!workspace.canOperate" @click="act('pause')">Pause</button><button class="danger" :disabled="!workspace.canOperate" @click="act('stop')">Stop</button><button :disabled="!workspace.canOperate" @click="act('reset')">Reset</button><button :disabled="!workspace.canOperate || !details.summary.deterministic" @click="tick">Advance 1s</button></div></article><article class="entity-card"><span class="eyebrow">Snapshot</span><h2>{{ details.summary.simulationTime }}</h2><p>{{ Object.keys(details.state).length }} datapoints · {{ details.faults.length }} active faults · {{ details.events.length }} recent events</p></article></section>
    <section v-else-if="tab === 'state'" class="list-panel"><div v-for="(value, name) in details.state" :key="name" class="state-edit-row"><div><strong>{{ name }}</strong><small>{{ details.definition.dataPoints.find(point => point.name === name)?.dataType }} · {{ details.definition.dataPoints.find(point => point.name === name)?.access }}</small></div><template v-if="writable.has(String(name))"><input v-model="stateDraft[name]" :aria-label="`Value for ${name}`" /><button :disabled="!workspace.canOperate" @click="write(String(name), value)">Write</button></template><code v-else>{{ JSON.stringify(value) }}</code></div></section>
    <section v-else-if="tab === 'definition'" class="editor-surface"><header class="editor-head"><div><span class="eyebrow">Revision {{ details.definition.version }}</span><h2>Logical definition</h2><p>Structural changes are available only after Stop.</p></div><button v-if="workspace.isAdmin && !editing" :disabled="details.summary.isRunning" @click="startEdit">Edit definition</button></header><div v-if="!editing" class="panel-body table-wrap"><table><thead><tr><th>Name</th><th>Type</th><th>Access</th><th>Initial</th><th>Unit</th></tr></thead><tbody><tr v-for="point in details.definition.dataPoints" :key="point.name"><td>{{ point.name }}</td><td>{{ point.dataType }}</td><td>{{ point.access }}</td><td>{{ JSON.stringify(point.initial) }}</td><td>{{ point.unit }}</td></tr></tbody></table></div><form v-else @submit.prevent="saveDefinition"><div class="editor-section"><div class="form-grid three"><div><label>Device type</label><input v-model="editor.form.type" /></div><div><label>Seed</label><input v-model.number="editor.form.seed" type="number" /></div><div class="check-field"><label><input v-model="editor.form.deterministic" type="checkbox" /> Deterministic</label></div></div></div><div class="editor-section"><div class="section-title"><div><h3>Datapoints</h3></div><button type="button" @click="editor.addDataPoint">Add datapoint</button></div><div v-for="(point,index) in editor.form.dataPoints" :key="index" class="binding-row definition-row"><input v-model="point.name" aria-label="Datapoint name" /><select v-model="point.dataType"><option v-for="type in ['Boolean','Int8','Int16','Int32','Int64','UInt8','UInt16','UInt32','UInt64','Float','Double','String']" :key="type">{{ type }}</option></select><select v-model="point.access"><option>Read</option><option>Write</option><option>ReadWrite</option></select><input v-model="point.initialText" aria-label="Initial value" /><button type="button" class="danger" @click="editor.removeDataPoint(index)">Remove</button></div></div><div class="editor-section"><div class="section-title"><div><h3>Protocol ports</h3></div><button type="button" @click="editor.addBinding">Add binding</button></div><div v-for="(binding,index) in editor.form.portBindings" :key="index" class="binding-row"><select v-model="binding.protocol" aria-label="Protocol"><option value="opcua">OPC UA</option><option value="modbus">Modbus TCP</option></select><input v-model.number="binding.port" type="number" min="1" max="65535" aria-label="Protocol port" /><button type="button" class="danger" @click="editor.removeBinding(index)">Remove</button></div></div><footer class="editor-footer"><button type="button" @click="editing = false">Cancel</button><button class="primary" type="submit">Save and replace host</button></footer></form></section>
    <section v-else-if="tab === 'protocols'" class="list-panel"><div v-if="details.definition.portBindings.length === 0" class="resource-state compact">No protocol ports reserved.</div><div v-for="binding in details.definition.portBindings" :key="`${binding.protocol}-${binding.port}`" class="list-row"><strong>{{ binding.protocol }}</strong><code>{{ binding.port }}</code></div></section>
    <section v-else-if="tab === 'scenarios'" class="list-panel"><div v-if="details.scenarios.available.length === 0" class="resource-state compact">No saved scenarios. Create one on the Scenarios page.</div><div v-for="scenario in details.scenarios.available" :key="scenario.id" class="list-row"><div><strong>{{ scenario.name }}</strong><small>{{ scenario.id }}</small></div><button :disabled="!workspace.canOperate" @click="runScenario(scenario.id)">Run</button></div></section>
    <section v-else-if="tab === 'faults'" class="editor-surface"><div class="editor-section"><div class="form-grid three"><div><label>Category</label><select v-model="fault.category"><option>Data</option><option>Device</option><option>Network</option></select></div><div><label>Type</label><input v-model="fault.type" /></div><div><label>Target</label><input v-model="fault.target" /></div></div><button class="danger action-row" :disabled="!workspace.canOperate" @click="activateFault">Activate fault</button></div><div class="fault-list panel-body"><div v-if="details.faults.length === 0" class="hint">No active faults.</div><div v-for="item in details.faults" :key="item.id" class="fault-row"><span>{{ item.id }} · {{ item.type }} · {{ item.target }}</span><button :disabled="!workspace.canOperate" @click="recover(item.id)">Recover</button></div></div></section>
    <section v-else class="event-terminal expanded"><div v-if="details.events.length === 0" class="event-empty">No recent runtime events.</div><div v-for="(event,index) in [...details.events].reverse()" :key="index" class="event-row"><span class="event-time">{{ index + 1 }}</span><span class="event-type">{{ event.eventType ?? event.type ?? 'RuntimeEvent' }}</span><span class="event-data">{{ JSON.stringify(event) }}</span></div></section>
  </template></ResourceState></main></template>
