<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { ApiProblemError, platformApi } from '../api'
import PageHeader from '../components/PageHeader.vue'
import ResourceState from '../components/ResourceState.vue'
import type { EffectiveSetting, SettingSummary } from '../types'

const settings = ref<SettingSummary[]>([]); const effective = ref<EffectiveSetting[]>([]); const loading = ref(true); const error = ref(''); const success = ref(''); const editing = ref(false)
const form = reactive({ key: '', type: 'String', valueText: '', version: 0 })
function infer(item: SettingSummary) { const value = JSON.parse(item.valueJson); return typeof value === 'string' ? 'String' : typeof value === 'number' ? 'Number' : typeof value === 'boolean' ? 'Boolean' : 'JSON' }
function display(item: SettingSummary) { try { return JSON.stringify(JSON.parse(item.valueJson), null, 2) } catch { return item.valueJson } }
async function load() { loading.value = true; try { [settings.value, effective.value] = await Promise.all([platformApi.settings(), platformApi.effectiveSettings()]); error.value = '' } catch (cause) { show(cause) } finally { loading.value = false } }
function add() { Object.assign(form, { key: '', type: 'String', valueText: '', version: 0 }); editing.value = true }
function edit(item: SettingSummary) { const type = infer(item); const value = JSON.parse(item.valueJson); Object.assign(form, { key: item.key, type, valueText: type === 'String' ? value : type === 'JSON' ? JSON.stringify(value, null, 2) : String(value), version: item.version }); editing.value = true }
function typedValue() { if (form.type === 'String') return form.valueText; if (form.type === 'Number') { const value = Number(form.valueText); if (!Number.isFinite(value)) throw new Error('Number settings require a finite numeric value.'); return value } if (form.type === 'Boolean') { if (!/^(true|false)$/i.test(form.valueText.trim())) throw new Error('Boolean settings require true or false.'); return form.valueText.trim().toLowerCase() === 'true' } return JSON.parse(form.valueText) }
async function save() { error.value = ''; try { const saved = await platformApi.saveSetting(form.key.trim(), { type: form.type, value: typedValue(), version: form.version }); success.value = `${saved.key} saved at revision ${saved.version}`; editing.value = false; await load() } catch (cause) { show(cause) } }
function show(cause: unknown) { error.value = cause instanceof ApiProblemError ? `${cause.message}${cause.errorCode ? ` (${cause.errorCode})` : ''}` : cause instanceof Error ? cause.message : String(cause) }
onMounted(load)
</script>

<template><main class="content"><PageHeader eyebrow="Admin" title="Platform settings" description="Edit typed, non-secret control-plane settings and compare them with the currently effective runtime configuration."><button class="primary" @click="add">Add setting</button></PageHeader>
  <div v-if="error" class="inline-error" role="alert">{{ error }}</div><div v-if="success" class="success-card" role="status">{{ success }}</div>
  <ResourceState :loading="loading" :error="''" :empty="false">
    <section class="settings-explainer"><div><span class="eyebrow">Effective runtime configuration</span><h2>What the process is using now</h2><p>These values are derived from the running host and are not automatically overwritten by the SQLite catalog.</p></div><div class="effective-grid"><article v-for="item in effective" :key="item.key"><strong>{{ item.key }}</strong><code>{{ JSON.stringify(item.value) }}</code><small>{{ item.source }}</small></article></div></section>
    <section v-if="editing" class="editor-surface setting-editor"><header class="editor-head"><div><span class="eyebrow">Persisted control plane</span><h2>{{ form.version ? 'Edit setting' : 'Add setting' }}</h2><p>Password, token, secret, credential, API key, and private key names are rejected.</p></div><button @click="editing = false">Cancel</button></header><form @submit.prevent="save"><div class="editor-section form-grid"><div><label>Key</label><input v-model="form.key" :disabled="form.version > 0" required /></div><div><label>Type</label><select v-model="form.type"><option>String</option><option>Number</option><option>Boolean</option><option>JSON</option></select></div><div class="wide"><label>Value</label><textarea v-if="form.type === 'JSON'" v-model="form.valueText" class="compact-textarea" spellcheck="false"></textarea><input v-else v-model="form.valueText" :placeholder="form.type === 'Boolean' ? 'true or false' : ''" required /></div></div><footer class="editor-footer"><span class="hint">Current revision: {{ form.version || 'new' }}</span><button class="primary" type="submit">Save setting</button></footer></form></section>
    <section class="persisted-settings"><header><div><span class="eyebrow">SQLite catalog</span><h2>Persisted control-plane settings</h2><p>Saving updates the catalog with optimistic version checking; runtime application remains explicit.</p></div></header><div v-if="settings.length === 0" class="resource-state compact">No persisted settings. Add a typed value to create the first catalog entry.</div><div v-else class="list-panel"><button v-for="setting in settings" :key="setting.key" class="list-row row-button" @click="edit(setting)"><div><strong>{{ setting.key }}</strong><small>{{ infer(setting) }} · revision {{ setting.version }}</small></div><code>{{ display(setting) }}</code></button></div></section>
  </ResourceState></main></template>
