<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { ApiProblemError, platformApi } from '../api'
import PageHeader from '../components/PageHeader.vue'
import ResourceState from '../components/ResourceState.vue'
import { useWorkspaceStore } from '../stores/workspace'
import type { SessionSummary, UserSummary } from '../types'

const workspace = useWorkspaceStore(); const session = ref<SessionSummary>(workspace.session); const users = ref<UserSummary[]>([]); const loading = ref(true); const error = ref(''); const success = ref('')
const createForm = reactive({ userName: '', password: '', role: 'Viewer' }); const bootstrapForm = reactive({ userName: 'admin', password: '' }); const loginForm = reactive({ userName: 'admin', password: '' }); const passwordForm = reactive({ currentPassword: '', newPassword: '' })
const roles = ['Admin', 'Operator', 'Viewer']
function show(cause: unknown) { error.value = cause instanceof ApiProblemError ? `${cause.message}${cause.errorCode ? ` (${cause.errorCode})` : ''}` : cause instanceof Error ? cause.message : String(cause) }
async function load() { loading.value = true; try { session.value = await platformApi.session(); workspace.session = session.value; users.value = session.value.mode === 'Disabled' || !session.value.authenticated ? [] : await platformApi.users(); error.value = '' } catch (cause) { show(cause) } finally { loading.value = false } }
async function bootstrap() { try { await platformApi.bootstrap(bootstrapForm); success.value = 'Administrator created. Use the sign-in form to continue.'; bootstrapForm.password = ''; await load() } catch (cause) { show(cause) } }
async function login() { try { await platformApi.login(loginForm); loginForm.password = ''; await load(); success.value = 'Signed in' } catch (cause) { show(cause) } }
async function createUser() { try { await platformApi.createUser(createForm); success.value = `${createForm.userName} created`; createForm.userName = ''; createForm.password = ''; await load() } catch (cause) { show(cause) } }
async function setRole(user: UserSummary, role: string) { try { await platformApi.updateUserRole(user.userName, role); success.value = `${user.userName} is now ${role}`; await load() } catch (cause) { show(cause) } }
async function remove(user: UserSummary) { if (!confirm(`Delete ${user.userName}?`)) return; try { await platformApi.deleteUser(user.userName); success.value = `${user.userName} deleted`; await load() } catch (cause) { show(cause) } }
async function changePassword() { try { await platformApi.changePassword(passwordForm); success.value = 'Password changed'; passwordForm.currentPassword = ''; passwordForm.newPassword = '' } catch (cause) { show(cause) } }
onMounted(load)
</script>

<template><main class="content"><PageHeader eyebrow="Admin" title="Users and roles" description="Manage the local identity boundary and Admin, Operator, and Viewer assignments." />
  <div v-if="error" class="inline-error" role="alert">{{ error }}</div><div v-if="success" class="success-card" role="status">{{ success }}</div>
  <ResourceState :loading="loading" :error="''" :empty="false">
    <section v-if="session.mode === 'Disabled'" class="auth-disabled"><span class="eyebrow">Authentication disabled</span><h2>Local developer access is active</h2><p>The runtime presents a virtual identity for local development. It is not inserted into the user database.</p><div class="identity-card"><div><strong>local-developer</strong><small>Effective local identity</small></div><span class="version-chip">Admin</span></div><p>Enable local identity authentication to bootstrap a persistent administrator and manage users.</p></section>
    <section v-else-if="!session.authenticated" class="admin-grid"><form class="editor-surface" @submit.prevent="bootstrap"><header class="editor-head"><div><span class="eyebrow">First administrator</span><h2>Bootstrap local identity</h2><p>This one-time action closes after the first user is created.</p></div></header><div class="editor-section"><label>Admin username</label><input v-model="bootstrapForm.userName" required /><label>Password</label><input v-model="bootstrapForm.password" type="password" autocomplete="new-password" required /></div><footer class="editor-footer"><span></span><button class="primary" type="submit">Create administrator</button></footer></form><form class="editor-surface" @submit.prevent="login"><header class="editor-head"><div><span class="eyebrow">Local identity</span><h2>Sign in</h2><p>The access token is kept in session storage and attached only to API requests.</p></div></header><div class="editor-section"><label>Username</label><input v-model="loginForm.userName" autocomplete="username" required /><label>Password</label><input v-model="loginForm.password" type="password" autocomplete="current-password" required /></div><footer class="editor-footer"><span></span><button type="submit">Sign in</button></footer></form></section>
    <template v-else>
      <section class="admin-grid"><form class="editor-surface" @submit.prevent="createUser"><header class="editor-head"><div><span class="eyebrow">Admin</span><h2>Add user</h2></div></header><div class="editor-section form-grid"><div><label>Username</label><input v-model="createForm.userName" required /></div><div><label>Role</label><select v-model="createForm.role"><option v-for="role in roles" :key="role">{{ role }}</option></select></div><div class="wide"><label>Password</label><input v-model="createForm.password" type="password" autocomplete="new-password" required /></div></div><footer class="editor-footer"><span class="hint">Credentials are sent only to Identity and never rendered again.</span><button class="primary" type="submit">Add user</button></footer></form>
        <form class="editor-surface" @submit.prevent="changePassword"><header class="editor-head"><div><span class="eyebrow">Current account</span><h2>Change password</h2></div></header><div class="editor-section"><label>Current password</label><input v-model="passwordForm.currentPassword" type="password" autocomplete="current-password" required /><label>New password</label><input v-model="passwordForm.newPassword" type="password" autocomplete="new-password" required /></div><footer class="editor-footer"><span></span><button type="submit">Update password</button></footer></form></section>
      <section class="list-panel user-list"><div v-if="users.length === 0" class="resource-state compact">No persistent users are available.</div><div v-for="user in users" :key="user.id" class="user-row"><div><strong>{{ user.userName }}</strong><small>{{ user.id }}</small></div><select :value="user.roles[0] ?? 'Viewer'" :aria-label="`Role for ${user.userName}`" @change="setRole(user, ($event.target as HTMLSelectElement).value)"><option v-for="role in roles" :key="role">{{ role }}</option></select><button class="danger" :disabled="user.userName === session.userName" @click="remove(user)">Delete</button></div></section>
    </template>
  </ResourceState></main></template>
